#!/usr/bin/env python3
# ---------------------------------------------------------------------------------
# Purpose: Initializes the local LiteLLM proxy environment across standard
#          Linux and WSL distributions using Python 3.11+ without systemd.
# ---------------------------------------------------------------------------------

import os
import sys
import shutil
import stat

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
RED, YELLOW = "\033[31m", "\033[33m"
RESET, BOLD, DIM = "\033[0m", "\033[1m", "\033[2m"

# Verify that all mandatory configuration assets exist before proceeding
print(">> Checking required files exist...")
requiredFiles = [
    "core/config.yaml",
    "core/routerHook.py",
    "core/litellm.env",
    "core/apiKeys.sh",
    "start.sh",
    "kill.sh",
    "query.py",
    "ui/server.py",
    "ui/index.html",
    "ui/style.css",
    "ui/script.js",
    "lib/memoryManager.py",
    "lib/skillLoader.py"
]

for f in requiredFiles:
    filePath = os.path.join(BASE_DIR, f)
    print(f">> Checking for file: {filePath} ... ", end="")
    if not os.path.exists(filePath):
        print(f"{RED}[ERROR] Missing {filePath}. Stopping setup.{RESET}")
        sys.exit(1)
    else: 
        print("[OK]")

# Ensure helper scripts are executable
print("\n>> Setting executable permissions on scripts...")
scripts_to_chmod = ["start.sh", "kill.sh", "query.py"]
for script in scripts_to_chmod:
    scriptPath = os.path.join(BASE_DIR, script)
    if os.path.exists(scriptPath):
        st = os.stat(scriptPath)
        os.chmod(scriptPath, st.st_mode | stat.S_IEXEC)
        print(f"  - Made {script} executable.")

## --------------------------------------------------------------------------------------
## Generate the Continue config using absolute paths relative to wherever this is cloned
## --------------------------------------------------------------------------------------
print("\n>> Generating dynamic Continue configuration...")
continueConfigContent = (
    "# ------------------------------------------------------------\n"
    "# Points the Continue VSCode extension at the local litellm proxy.\n"
    "# Automatically generated by setup.py based on repo location.\n"
    "# ------------------------------------------------------------\n\n"
    "models:\n"
    "  - name: local-router\n"
    "    provider: openai\n"
    "    model: auto\n"
    "    apiBase: http://localhost:4000\n"
    "    apiKey: sk-anything\n"
)
continueDir = os.path.expanduser("~/.continue")
if not os.path.exists(continueDir):
    print(f"{DIM}>> Directory does not exist. Creating directory: {continueDir}{RESET}")
    os.makedirs(continueDir)
else: 
    print(f"{DIM}>> Directory already exists: {continueDir}{RESET}")

continueDest = os.path.join(continueDir, "config.yaml")
print(f">> Creating/Overwriting Continue config file at: {continueDest}")
with open(continueDest, "w") as f: 
    f.write(continueConfigContent)
print(f"{YELLOW}>> Wrote Continue configuration to {continueDest}{RESET}")

## --------------------------------------------------
## Generate the systemd service using absolute paths
## --------------------------------------------------
print("\n>> Generating systemd service file with dynamic paths...")
serviceContent = (
    "# Runs the litellm proxy as a background service inside WSL.\n"
    "[Unit]\n"
    "Description=LiteLLM proxy\n"
    "After=network.target\n\n"
    "[Service]\n"
    f"WorkingDirectory={BASE_DIR}\n"
    f"Environment=PYTHONPATH={BASE_DIR}\n"
    f"EnvironmentFile={BASE_DIR}/core/litellm.env\n"
    f"ExecStart={os.path.expanduser('~/.local/bin/litellm')} --config {BASE_DIR}/core/config.yaml --port 4000\n"
    "Restart=on-failure\n\n"
    "[Install]\n"
    "WantedBy=default.target\n"
)
systemdDir = os.path.expanduser("~/.config/systemd/user")
if not os.path.exists(systemdDir):
    print(f"{DIM}>> Directory does not exist. Creating directory: {systemdDir}{RESET}")
    os.makedirs(systemdDir)
else: 
    print(f"{DIM}>> Directory already exists: {systemdDir}{RESET}")

print(f">> Creating/Overwriting systemd service file at: {os.path.join(systemdDir, 'litellm.service')}")
with open(os.path.join(systemdDir, "litellm.service"), "w") as f: 
    f.write(serviceContent)
print(f"{YELLOW}>> Wrote systemd service file to {os.path.join(systemdDir, 'litellm.service')}{RESET}")

## --------------------------------------------------------------------------
## Locate the actual LiteLLM executable within the active Python environment
## --------------------------------------------------------------------------
print("\n>> Symlinking litellm from active environment...")
condaBin = os.path.join(os.path.dirname(sys.executable), "litellm")
print(f">> Searching for litellm binary at primary path: {condaBin}")
if not os.path.isfile(condaBin):
    print(">> Primary path not found. Falling back to shutil.which('litellm')")
    condaBin = shutil.which("litellm")
if not condaBin or not os.path.isfile(condaBin):
    print(f"{RED}[ERROR] litellm binary not found in active environment.{RESET}")
    sys.exit(1)
print(f"{YELLOW}>> Successfully located litellm binary at: {condaBin}{RESET}")

## ----------------------------------------------------------------------------------
## Ensure local binary directory exists and symlink the binary for global CLI access
## ----------------------------------------------------------------------------------
localBin = os.path.expanduser("~/.local/bin")
if not os.path.exists(localBin):
    print(f"{DIM}>> Directory does not exist. Creating local bin directory: {localBin}{RESET}")
    os.makedirs(localBin)
else: 
    print(f"{DIM}>> Local bin directory already exists: {localBin}{RESET}")

localLitellm = os.path.join(localBin, "litellm")
if os.path.lexists(localLitellm):
    print(f">> Found existing file/symlink at target destination. Removing: {localLitellm}")
    os.remove(localLitellm)

print(f">> Creating symlink for global CLI access:")
print(f">> Source (Target): {condaBin}")
print(f">> Destination (Link name): {localLitellm}")
os.symlink(condaBin, localLitellm)
print(f"{YELLOW}>> Symlink successfully created at {localLitellm}{RESET}")

print("\n>> Setup complete. Run systemctl --user daemon-reload if using systemd.")
