#!/usr/bin/env python3
# ---------------------------------------------------------------------------------
# Purpose: Initializes the local LiteLLM proxy environment across standard
#          Linux and WSL distributions using Python 3.11+ without systemd.
# Actions Performed:
#    1. Verifies the presence of required configuration files.
#    2. Creates necessary directories for Continue and local binaries.
#    3. Generates the Continue config and systemd files dynamically with absolute paths.
#    4. Directly symlinks the environment's LiteLLM binary to ~/.local/bin/litellm.
# ---------------------------------------------------------------------------------

import os
import sys
import shutil
BASE_DIR = os.path.dirname(os.path.abspath(__file__))

# Verify that all mandatory configuration assets exist before proceeding
print(">> Checking required files exist...")
requiredFiles = [
    "core/config.yaml",
    "core/routerHook.py",
    "core/litellm.env",
    "core/apiKeys.sh",
    "start.sh"
]

for f in requiredFiles:
    filePath = os.path.join(BASE_DIR, f)
    print(f"   -> Checking for file: {filePath}")
    if not os.path.isfile(filePath):
        print(f"      [ERROR] Missing {filePath} - stopping setup.")
        sys.exit(1)
    else:
        print(f"      [OK] Found {filePath}")

# Generate the Continue config using absolute paths relative to wherever this is cloned
print("\n>> Generating dynamic Continue configuration...")
continueConfigContent = (
    "# ------------------------------------------------------------\n"
    "# Points the Continue VSCode extension at the local litellm proxy.\n"
    "# Automatically generated by setup.py based on repo location.\n"
    "# ------------------------------------------------------------\n\n"
    "models:\n"
    "  - name: local-router\n"
    "    provider: openai\n"
    "    model: auto\n"
    "    apiBase: http://localhost:4000\n"
    "    apiKey: sk-anything\n"
)
continueDir = os.path.expanduser("~/.continue")
if not os.path.exists(continueDir):
    print(f"   -> Directory does not exist. Creating directory: {continueDir}")
    os.makedirs(continueDir)
else:
    print(f"   -> Directory already exists: {continueDir}")

continueDest = os.path.join(continueDir, "config.yaml")
print(f"   -> Creating/Overwriting Continue config file at: {continueDest}")
with open(continueDest, "w") as f: f.write(continueConfigContent)
print(f"      [OK] Wrote Continue configuration to {continueDest}")

# Generate the systemd service using absolute paths
print("\n>> Generating systemd service file with dynamic paths...")
serviceContent = (
    "# Runs the litellm proxy as a background service inside WSL.\n"
    "[Unit]\n"
    "Description=LiteLLM proxy\n"
    "After=network.target\n\n"
    "[Service]\n"
    f"WorkingDirectory={BASE_DIR}\n"
    f"Environment=PYTHONPATH={BASE_DIR}\n"
    f"EnvironmentFile={BASE_DIR}/core/litellm.env\n"
    f"ExecStart={os.path.expanduser('~/.local/bin/litellm')} --config {BASE_DIR}/core/config.yaml --port 4000\n"
    "Restart=on-failure\n\n"
    "[Install]\n"
    "WantedBy=default.target\n"
)

systemdDir = os.path.expanduser("~/.config/systemd/user")
if not os.path.exists(systemdDir):
    print(f"   -> Directory does not exist. Creating directory: {systemdDir}")
    os.makedirs(systemdDir)
else:
    print(f"   -> Directory already exists: {systemdDir}")

print(f"   -> Creating/Overwriting systemd service file at: {os.path.join(systemdDir, 'litellm.service')}")
with open(os.path.join(systemdDir, "litellm.service"), "w") as f: f.write(serviceContent)
print(f"      [OK] Wrote systemd service file to {os.path.join(systemdDir, 'litellm.service')}")

# Locate the actual LiteLLM executable within the active Python environment
print("\n>> Symlinking litellm from active environment...")
condaBin = os.path.join(os.path.dirname(sys.executable), "litellm")
print(f"   -> Searching for litellm binary at primary path: {condaBin}")
if not os.path.isfile(condaBin):
    print("   -> Primary path not found. Falling back to shutil.which('litellm')")
    condaBin = shutil.which("litellm")

if not condaBin or not os.path.isfile(condaBin):
    print("[ERROR] litellm binary not found in active environment.")
    sys.exit(1)
print(f"   -> Successfully located litellm binary at: {condaBin}")

# Ensure local binary directory exists and symlink the binary for global CLI access
localBin = os.path.expanduser("~/.local/bin")
if not os.path.exists(localBin):
    print(f"   -> Directory does not exist. Creating local bin directory: {localBin}")
    os.makedirs(localBin)
else:
    print(f"   -> Local bin directory already exists: {localBin}")

localLitellm = os.path.join(localBin, "litellm")
if os.path.lexists(localLitellm):
    print(f"   -> Found existing file/symlink at target destination. Removing: {localLitellm}")
    os.remove(localLitellm)

print(f"   -> Creating symlink for global CLI access:")
print(f"      Source (Target): {condaBin}")
print(f"      Destination (Link name): {localLitellm}")
os.symlink(condaBin, localLitellm)
print(f"      [OK] Symlink successfully created at {localLitellm}")

print("\n>> Setup complete. Run systemctl --user daemon-reload if using systemd.")
