#!/usr/bin/env bash
# -------------------------------------------------------------------------
# Unified startup script for hazar-ai services.
# Usage: ./start.sh [proxy|local|ui|all|fresh|offline]
# -------------------------------------------------------------------------

cd "$(dirname "$0")" || exit 1
COMMAND=${1:-all}
YELLOW='\033[33m'
BOLD_YELLOW='\033[1;33m'
RESET='\033[0m'

## Always start from a clean slate: kill any previously running proxy, UI,
## or local model server before doing anything else. This avoids stacking
## up duplicate background processes (and stale port binds) every time
## start.sh is re-run.
echo ">> Killing any existing hazar-ai services first..."
bash kill.sh

## Securely load API keys and environment variables into the shell session.
## 'set -a' exports all variables defined in the sourced file automatically.
if [ -f core/litellm.env ]; then
    set -a
    source core/litellm.env
    set +a
fi

## Safeguard against a missing master key. The proxy requires this to authenticate
## incoming local requests. If missing, a default is injected.
if [ -z "$LITELLM_MASTER_KEY" ]; then
    echo ">> LITELLM_MASTER_KEY is not set. Injecting default key into core/litellm.env..."
    echo 'LITELLM_MASTER_KEY="sk-anything"' >> core/litellm.env
    export LITELLM_MASTER_KEY="sk-anything"
fi

## Boots the core LiteLLM proxy in the background on port 4000, using the
## given config file (defaults to the standard cloud+local config).
start_proxy() {
    local config_file=${1:-core/config.yaml}
    echo ">> Starting LiteLLM proxy on port 4000 (config: $config_file)..."
    nohup setsid litellm --config "$config_file" --port 4000 > core/litellm.log 2>&1 &
    echo ">> LiteLLM proxy started (PID $!)."
}

## Scans models/ for every .gguf file and boots one llama.cpp inference
## server per model, on sequential ports starting at 8000. Also writes
## core/config.local.generated.yaml so the proxy can reach every model
## found, under aliases "local" (the first model found) and
## "local:<filename-without-extension>" (every model, individually).
## Sets LOCAL_MODEL_COUNT so callers can tell whether anything was found.
start_local() {
    MODEL_DIR="./models"
    mkdir -p "$MODEL_DIR"
    mapfile -t MODEL_FILES < <(ls "$MODEL_DIR"/*.gguf 2>/dev/null)

    LOCAL_MODEL_COUNT=${#MODEL_FILES[@]}
    if [ "$LOCAL_MODEL_COUNT" -eq 0 ]; then
        echo ">> No .gguf models found in $MODEL_DIR. Skipping local inference server(s)."
        return
    fi

    echo ">> Found $LOCAL_MODEL_COUNT local model(s) in $MODEL_DIR. Starting one server per model..."

    local port=8000
    local entries=""
    for model_file in "${MODEL_FILES[@]}"; do
        local model_name
        model_name=$(basename "$model_file")
        model_name="${model_name%.gguf}"

        echo ">> Starting local inference server for $model_file on port $port (alias: local:$model_name)..."
        nohup setsid python3 -m llama_cpp.server --model "$model_file" --port "$port" --host 127.0.0.1 \
            > "core/local_model_${model_name}.log" 2>&1 &
        echo ">> Local inference server started (PID $!)."

        entries="${entries}  - model_name: local:${model_name}\n    litellm_params:\n      model: openai/local\n      api_base: http://localhost:${port}/v1\n      api_key: sk-local\n"
        # The first model found is also registered under the plain "local" alias,
        # so existing CLI/Web UI usage of --model local keeps working unchanged.
        if [ "$port" -eq 8000 ]; then
            entries="${entries}  - model_name: local\n    litellm_params:\n      model: openai/local\n      api_base: http://localhost:${port}/v1\n      api_key: sk-local\n"
        fi
        port=$((port + 1))
    done

    ## Regenerate the local-only proxy config used by "offline" mode, and by
    ## anything that wants to talk to a specific local model via its alias.
    {
        echo "# Auto-generated by start.sh — do not edit by hand."
        echo "# Lists every .gguf model found under models/, one per llama.cpp server."
        echo "model_list:"
        echo -e "$entries"
        echo "router_settings:"
        echo "  routing_strategy: usage-based-routing"
        echo "general_settings:"
        echo "  master_key: os.environ/LITELLM_MASTER_KEY"
    } > core/config.local.generated.yaml
    echo ">> Wrote core/config.local.generated.yaml with $LOCAL_MODEL_COUNT local model alias(es)."
}

## Boots the local Python web server to host the browser UI.
start_ui() {
    echo ">> Starting Web UI on port 5000..."
    nohup setsid python3 ui/server.py > core/ui.log 2>&1 &
    echo ">> Web UI started (PID $!)."
}

# -------------------------------------------------------------------------
# Execution Routing
# -------------------------------------------------------------------------
case "$COMMAND" in
    # The 'fresh' argument wipes previous memory caches before starting
    fresh)
        echo ">> Starting fresh session. Clearing previous memory databases..."
        python3 query.py --clear-memory
        start_proxy
        start_local
        start_ui
        ;;
    proxy)
        start_proxy
        ;;
    local)
        start_local
        ;;
    ui)
        start_ui
        ;;
    all)
        start_proxy
        start_local
        start_ui
        ;;
    # 'offline' only starts local .gguf model server(s) plus a proxy pointed
    # at the generated local-only config, so no cloud API key is ever
    # contacted. Use --model local (or local:<name>) with query.py/the Web UI.
    offline)
        start_local
        if [ "${LOCAL_MODEL_COUNT:-0}" -eq 0 ]; then
            echo ">> [ERROR] No .gguf models found in ./models — nothing to run offline."
            exit 1
        fi
        start_proxy core/config.local.generated.yaml
        start_ui
        ;;
    *)
        echo "Usage: $0 {proxy|local|ui|all|fresh|offline}"
        exit 1
        ;;
esac

## Provide helpful CLI feedback and tail the proxy logs for live monitoring
if [[ "$COMMAND" == "all" || "$COMMAND" == "fresh" || "$COMMAND" == "offline" ]]; then
    echo ""
    echo -e ">> Web UI is live at: ${BOLD_YELLOW}http://localhost:5000${RESET}"
    echo ">> CLI Usage Examples:"
    echo -e "   ${YELLOW}python3 query.py --query \"Write a script to parse JSON.\"${RESET}"
    echo -e "   ${YELLOW}python3 query.py --model fast --query \"Quick question...\"${RESET}"
    echo -e "   ${YELLOW}python3 query.py --query \"Long output\" --max-tokens 2000${RESET}"
    echo -e "   ${YELLOW}python3 query.py --query \"Analyze this\" --file app.py config.json --optimize-tokens${RESET}"
    echo -e "   ${YELLOW}python3 query.py --query \"With skill\" --skill prompt-master${RESET}"
    echo -e "   ${YELLOW}python3 query.py --query \"One-off question\" --no-memory${RESET}"
    echo -e "   ${YELLOW}python3 query.py --memory-status${RESET}"
    echo -e "   ${YELLOW}python3 query.py --clear-memory${RESET}"
    echo -e "   ${YELLOW}python3 query.py --list-skills${RESET}"
    echo -e "   ${YELLOW}python3 query.py --skill-inspect prompt-master${RESET}"
    if [[ "$COMMAND" == "offline" ]]; then
        echo -e "   ${YELLOW}python3 query.py --model local --query \"Fully offline query...\"${RESET}"
    fi
    echo ""
    echo ">> All services initiated. Tailing proxy logs (Press Ctrl+C to exit log view)..."
    sleep 1
    tail -f core/litellm.log
fi
