#!/usr/bin/env python3
# ----------------------------------------------------------------------------
# Local model gateway configs
#
# Builds gateway entries for the GGUF servers started by start.sh.
# Normal startup keeps cloud routes and adds every local model alias.
# Offline startup gets a separate config containing only local routes.
# YAML serialization handles spaces and punctuation in model filenames.
# ----------------------------------------------------------------------------

import copy
import os
import sys
import yaml
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

def generateConfigs(modelFiles, baseDirectory=BASE_DIR):
    # -----------------------------------------------------------------------
    # Register one server per model and preserve cloud routes in normal mode.
    # start.sh passes filenames in its exact startup order. The first server
    # also receives the plain local alias. YAML serialization quotes unusual
    # filenames correctly. The offline config contains only local routes and
    # excludes cloud callbacks and cloud fallback chains.
    # -----------------------------------------------------------------------
    
    ## Use the exact startup order; entry zero maps to port 8000, entry one to 8001, and so on.
    localEntries = []
    for index, filename in enumerate(modelFiles):
        modelName = os.path.splitext(os.path.basename(filename))[0]
        entry = {
            "model_name": f"local:{modelName}",
            "litellm_params": {
                "model": "openai/local",
                "api_base": f"http://127.0.0.1:{8000 + index}/v1",
                "api_key": "sk-local",
            },
        }
        localEntries.append(entry)
        ## The first model also gets the plain local alias for existing CLI/UI requests.
        if index == 0:
            default = copy.deepcopy(entry)
            default["model_name"] = "local"
            localEntries.append(default)
    coreDirectory = os.path.join(baseDirectory, "core")
    with open(os.path.join(coreDirectory, "config.yaml"), encoding="utf-8") as configFile:
        runtime = yaml.safe_load(configFile)
        
    ## Remove the old local placeholder before adding the newly discovered models.
    cloudEntries = []
    for entry in runtime.get("model_list", []):
        name = entry.get("model_name", "")
        if name != "local" and not name.startswith("local:"): cloudEntries.append(entry)
    runtime["model_list"] = cloudEntries + localEntries
    
    ## The offline file has no cloud callback or cloud fallback chain.
    offline = {
        "model_list": localEntries,
        "router_settings": {"routing_strategy": "usage-based-routing"},
        "general_settings": {"master_key": "os.environ/LITELLM_MASTER_KEY"},
    }
    configs = {
        "config.runtime.generated.yaml": runtime,
        "config.local.generated.yaml": offline,
    }
    ## Write generated files separately; the hand-edited cloud config stays intact.
    for name, config in configs.items():
        with open(os.path.join(coreDirectory, name), "w", encoding="utf-8") as configFile:
            configFile.write("# Generated by start.sh; edit core/config.yaml for cloud routes.\n")
            yaml.safe_dump(config, configFile, sort_keys=False, allow_unicode=True)
    return configs

if __name__ == "__main__": generateConfigs(sys.argv[1:])
