#!/usr/bin/env python3
# ----------------------------------------------------------------------------
# Local model gateway configs
#
# Builds gateway entries for the lazy-loading local server started by start.sh.
# Normal startup keeps cloud routes and adds every local model alias.
# Offline startup gets a separate config containing only local routes.
# YAML serialization handles spaces and punctuation in model filenames.
# ----------------------------------------------------------------------------

import copy
import os
import sys
import yaml
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

## Share model discovery with the CLI, browser backend, and inference service.
sys.path.insert(0, os.path.join(BASE_DIR, "lib"))
from localModels import scanModels

def generateConfigs(modelFiles=None, baseDirectory=BASE_DIR):
    # -----------------------------------------------------------------------
    # Register discovered models on one shared inference service.
    # Relative filenames and folder paths provide stable local aliases.
    # The first discovered model also receives the plain local alias.
    # Normal configuration preserves cloud routes; offline contains local only.
    # -----------------------------------------------------------------------

    ## Every route shares port 8000; only the requested model is loaded.
    localEntries = []
    modelDirectory = os.path.join(baseDirectory, "models")

    for index, model in enumerate(scanModels(modelDirectory)):
        entry = {
            "model_name": model["id"],
            "litellm_params": {
                "model": "openai/" + model["id"],
                "api_base": "http://127.0.0.1:8000/v1",
                "api_key": "os.environ/LITELLM_MASTER_KEY",
            },
        }
        localEntries.append(entry)

        ## Preserve the existing default local route.
        if index == 0:
            default = copy.deepcopy(entry)
            default["model_name"] = "local"
            localEntries.append(default)
        
    coreDirectory = os.path.join(baseDirectory, "core")
    with open(os.path.join(coreDirectory, "config.yaml"), encoding="utf-8") as configFile:
        runtime = yaml.safe_load(configFile)
        
    ## Remove the old local placeholder before adding the newly discovered models.
    cloudEntries = []
    for entry in runtime.get("model_list", []):
        name = entry.get("model_name", "")
        if name != "local" and not name.startswith("local:"): cloudEntries.append(entry)
    runtime["model_list"] = cloudEntries + localEntries
    
    ## The offline file has no cloud callback or cloud fallback chain.
    offline = {
        "model_list": localEntries,
        "router_settings": {"routing_strategy": "usage-based-routing"},
        "general_settings": {"master_key": "os.environ/LITELLM_MASTER_KEY"},
    }
    configs = {
        "config.runtime.generated.yaml": runtime,
        "config.local.generated.yaml": offline,
    }
    ## Write generated files separately; the hand-edited cloud config stays intact.
    for name, config in configs.items():
        with open(os.path.join(coreDirectory, name), "w", encoding="utf-8") as configFile:
            configFile.write("# Generated by start.sh; edit core/config.yaml for cloud routes.\n")
            yaml.safe_dump(config, configFile, sort_keys=False, allow_unicode=True)
    return configs

if __name__ == "__main__": generateConfigs(sys.argv[1:])
